name = "TableOperations"
uuid = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.2.0"

[deps]
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
SentinelArrays = "1"
Tables = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
